### ISSUE TITLE
How to configure ?

### ISSUE THREAD

**Issue by vaheqelyan** [co1ncidence/monokai-pro.vim#6]
How can I properly configure this theme to look the same as in README.

```vim
syntax enable
colorscheme monokai-pro
```
![image](https://user-images.githubusercontent.com/14107127/101991232-bd2c8480-3cc4-11eb-899a-40e23abd511a.png)

My result

![image](https://user-images.githubusercontent.com/14107127/101991251-d8978f80-3cc4-11eb-85f4-4d5047e7000f.png)

**Comment by co1ncidence** [comment]
Make sure you are using a terminal which supports true color (such as Alacritty or Simple Terminal). That should be the only problem here.

**Comment by vaheqelyan** [comment]
thanks, my fault. I had to add
```vim
if has('termguicolors')
set termguicolors
endif
```
