### ISSUE TITLE
How Install

### ISSUE THREAD

**Issue by pwndumb** [co1ncidence/monokai-pro.vim#7]
Its possible install this theme with vim-plug ?

**Comment by pwndumb** [comment]
Its possible install this theme with vim-plug ?

**Comment by co1ncidence** [comment]
It sure is, just add:
```vim
plug co1ncidence/monokai-pro.vim
```
to your plugins block, and then set `colorscheme monokai-pro` in your `.vimrc` (or equivalent file).

**Comment by exorcist365** [comment]
Dont forget the single or  double quotes like so
```vim
Plug 'co1ncidence/molokai-pro.vim'
```

**Comment by jaydenramm** [comment]
Ayy, ayy, vim-plug walk (vim-plug walk, plug, plug)
I don't even understand how the fuck my vim-plug talk (huh? what, what?)
Pick him up in a space coupe,
I don't let my vim-plug walk (skrrt, pull up in a space coupe)

https://user-images.githubusercontent.com/41844899/103491795-8a0f8800-4e61-11eb-98c2-85046c8a895a.mp4

**Comment by co1ncidence** [comment]
> Dont forget the single or double quotes like so
> 
> ```viml
> Plug 'co1ncidence/monokai-pro.vim'
> ```

Apologies Mr. Exorcist but since my keyboard is 100% GNU/Libre free hardware, it does not support the nonfree `'` and `"` characters, please do not make such egregious suggestions again, they are unnecesary.

Regards,

Jayden Ramm.

**Comment by jaydenramm** [comment]
> > Dont forget the single or double quotes like so
> > ```viml
> > Plug 'co1ncidence/monokai-pro.vim'
> > ```
> 
> Apologies Mr. Exorcist but since my keyboard is 100% GNU/Libre free hardware, it does not support the nonfree `'` and `"` characters, please do not make such egregious suggestions again, they are unnecesary.
> 
> Regards,
> 
> Jayden Ramm.

![f25b1e5bf73a918c836f6e00cc1142c0](https://user-images.githubusercontent.com/41844899/103492316-fd66c900-4e64-11eb-97ef-4d964dc2fb68.png)

**Comment by pwndumb** [comment]
> It sure is, just add:
> 
> ```viml
> plug co1ncidence/monokai-pro.vim
> ```
> 
> to your plugins block, and then set `colorscheme monokai-pro` in your `.vimrc` (or equivalent file).

Its a nice and beautiful theme. I enjoy a lot.
